# -*- coding: utf-8 -*-
"""Trabalho1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lU585fGJqlW4tix7aCmlJGEOBjlFdk5
"""

# Passo 1 - Montar Google Drive
from google.colab import drive
drive.mount("/content/drive")

import pandas as pd

# file = open("/content/drive/MyDrive/00AA-Doutorado/Gregio/Trabalho-Final/fake_job_postings.csv")
file = open("fake_job_postings.csv")

df = pd.read_csv(file)
df

df.describe()

df.info()

# soma NaNs de cada coluna
df.isna().sum()